# Generated by Django 3.0.2 on 2020-09-15 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Patient_Name', models.CharField(max_length=100, unique=True)),
                ('Patient_Age', models.IntegerField()),
                ('Reason_of_concern', models.CharField(max_length=200)),
                ('Patient_Contact', models.IntegerField()),
                ('Patient_Address', models.CharField(max_length=200)),
                ('DATE', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CriticalCare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Patient_Name', models.CharField(max_length=100)),
                ('Patient_Age', models.IntegerField()),
                ('Reason_of_concern', models.CharField(max_length=200)),
                ('Patient_Contact', models.IntegerField()),
                ('Patient_Address', models.CharField(max_length=200)),
                ('DATE', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='DoctorsRecruitment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Contact_Number', models.IntegerField()),
                ('Address', models.CharField(max_length=200)),
                ('Specialization', models.CharField(max_length=50)),
                ('Degree', models.CharField(max_length=50)),
                ('Passout_Year', models.IntegerField()),
                ('Experience', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HealthCheckup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Patient_Name', models.CharField(max_length=100)),
                ('Patient_Age', models.IntegerField()),
                ('Reason_of_concern', models.CharField(max_length=200)),
                ('Patient_Contact', models.IntegerField()),
                ('Patient_Address', models.CharField(max_length=200)),
                ('DATE', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('City', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ambulance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Patient_Name', models.CharField(max_length=100)),
                ('Patient_Contact', models.IntegerField()),
                ('Patient_Address', models.CharField(max_length=200)),
                ('DATE', models.DateField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital.Location')),
            ],
        ),
    ]
