# Generated by Django 3.0.2 on 2020-09-15 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ambulance',
            name='location',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
