# Generated by Django 3.0.2 on 2020-09-15 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0003_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
