# Generated by Django 3.0.2 on 2020-09-15 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0004_delete_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itself',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
            ],
        ),
    ]
