# Generated by Django 3.0.2 on 2020-09-15 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0006_auto_20200915_2339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('City', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Itself',
        ),
        migrations.AddField(
            model_name='ambulance',
            name='location',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='Hospital.Location'),
            preserve_default=False,
        ),
    ]
